# Generated by Django 2.2.5 on 2020-05-14 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0003_auto_20200514_1015'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='coursecomments',
        #     name='course',
        #     field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='coursecomments',
        #     name='user',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='usercourse',
        #     name='course',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='usercourse',
        #     name='user',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='userfavorite',
        #     name='user',
        #     field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        #     preserve_default=False,
        # ),
    ]
